# Generated by Django 2.2.9 on 2020-02-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_station_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_station_name',
        ),
    ]
