# Generated by Django 2.2.9 on 2020-05-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200526_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='route',
        ),
        migrations.RemoveField(
            model_name='time',
            name='station',
        ),
        migrations.CreateModel(
            name='StationRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Station')),
            ],
        ),
        migrations.AddField(
            model_name='time',
            name='station_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.StationRoute'),
            preserve_default=False,
        ),
    ]
