# Generated by Django 2.2.9 on 2020-07-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200526_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationroute',
            name='up_down_direction',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
