# Generated by Django 2.2.9 on 2020-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stationroute_up_down_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='holiday_type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
