# Generated by Django 2.2.9 on 2020-07-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_time_holiday_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StationOtherName',
            new_name='StationSynonym',
        ),
        migrations.RenameField(
            model_name='stationsynonym',
            old_name='other_station_name',
            new_name='synonym',
        ),
    ]
